# Generated by Django 4.1.2 on 2022-10-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='preferred_program',
            field=models.CharField(choices=[('- Select -', '- Select -'), ('Volunteer Services', 'Volunteer Services'), ('Investment supervision, coordination and implementation', 'Investment supervision, coordination and implementation'), ('Project Management', 'Project Management'), ('Workshops & Training', 'Workshops & Training'), ('Career Counselling', 'Career Counselling')], max_length=150),
        ),
    ]
