# Generated by Django 4.1.2 on 2022-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_volunteerapplication_preferred_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='preferred_package',
            field=models.CharField(choices=[('- Select -', '- Select -'), ('Families', 'Families'), ('Friends', 'Friends'), ('Students', 'Students'), ('Employees', 'Employees'), ('Individuals', 'Individuals'), ('Teachers', 'Teachers')], max_length=50),
        ),
    ]
