# Generated by Django 4.1.2 on 2022-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_volunteerapplication_preferred_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='any_other_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='date_of_application',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='date_of_travel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='do_you_require_further_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='duration_of_stay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='education_or_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_residential_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='emergency_contact_telephone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='health_conditions_disabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, choices=[('- Select -', '- Select -'), ('Through a friend', 'Through a friend'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Blog Post', 'Blog Post'), ('Word of Mouth', 'Word of Mouth'), ('Email', 'Email'), ('Online Ad', 'Online Ad'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='personalized_preferrences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='preferred_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='preferred_package',
            field=models.CharField(blank=True, choices=[('- Select -', '- Select -'), ('Families', 'Families'), ('Friends', 'Friends'), ('Students', 'Students'), ('Employees', 'Employees'), ('Individuals', 'Individuals'), ('Teachers', 'Teachers')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='referee_contact_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='referee_contact_organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='referee_contact_telephone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='referee_contact_work_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='travel_pack',
            field=models.CharField(blank=True, choices=[('- Select -', '- Select -'), ('Individual', 'Individual'), ('Group', 'Group')], max_length=50, null=True),
        ),
    ]
